Exit with error if any libraries uncopyable

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -19,6 +19,10 @@ for lib in \
   neopixel.mpy
 do
   echo "Copying ${lib}"
+  if [ ! -r "${LIB_PATH}/${lib}" ]; then
+    echo "ERROR: Unable to copy: ${LIB_PATH}/${lib}"
+    exit 1
+  fi
   cp -pr "${LIB_PATH}/${lib}" build/lib
 done
 
